### ISSUE TITLE
bug: no fallback docs link on unsupported language

### ISSUE THREAD

**Issue by pemassi** [logto-io/docs#215]
### What problem did you meet?

I am trying to add a new language(Korean) to `Logto` application (https://github.com/logto-io/logto/pull/1677). If I click the `Docs` from the sidebar in the admin console, it will open new page which is `https://docs.logto.io/ko-kr`. Then I will see the below image.

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/10739332/181761522-ed8e6d4f-b938-447b-b0bb-bfba4bf1d3aa.png">

### Describe what you'd like Logto to have

If there is no translation for that language, it should be a fallback to English for the developer.

**Comment by demonzoo** [comment]
Yeah, that makes sense. Thanks for reporting!
